FLK-1575 - Provide implementations for module 1 labs
Cristian34/flink-training pull request #1
Opened 2024-07-10 10:37 UTC by Cristian34

Implementations for the 4 labs required for Flink Training - Module 1

1. Ride Cleansing
- basic implementation testing the "filter" transformation

2. Rides and Fares
- implementation connecting 2 streams (for TaxiFare and TaxiRide) into one single stream of "RideAndFare"
- uses 2 value states to store rides and fares

3. Hourly tips
- outputs the driver with the largest sum of tips per hour
- uses keyed windows and a global window
- combines a reduce and a process window function to reduce state storage for the process window function
- for clarity, created a POJO class to store driver fares per hour 

4. Long rides
- outputs the rides longer than a maximum duration time (2 hours)
- uses a value state to register the first occurred ride (START or END event) and a timer to detect long rides
when the START event occurs first

Observation: all tests are passing

2024-07-11 14:16 UTC, ness-RazvanFilip commented on rides-and-fares/src/main/java/org/apache/flink/training/exercises/ridesandfares/RidesAndFaresExercise.java
> +        private ValueState<TaxiFare> fareState;
All Flink state must be made transient so that the state value is not serialized and not shared across multiple Flink task managers. https://stackoverflow.com/a/72558397

2024-07-11 14:25 UTC, ness-RazvanFilip commented on long-ride-alerts/src/main/java/org/apache/flink/training/exercises/longrides/LongRidesExercise.java
> +        private ValueState<TaxiRide> registeredRide;
Remember to mark the value state field as transient

2024-07-11 14:50 UTC, ness-RazvanFilip commented on long-ride-alerts/src/main/java/org/apache/flink/training/exercises/longrides/LongRidesExercise.java
> +                    registeredRide.update(ride);
Start events may indeed arrive later than the corresponding end event, for any reason (network lag, processing lag, etc.).
This stream has been configured to allow 60s out-of-orderness, and you correctly drop messages that are earlier than the current watermark.

So a start event of t=1 may arrive after the end event of t=70. In this case, the start event will be ignored, and the end event will remain in the state, leaking memory. Can you come up with a solution to clear the registeredRide for this situation?

2024-07-11 14:53 UTC, ness-RazvanFilip commented on long-ride-alerts/src/main/java/org/apache/flink/training/exercises/longrides/LongRidesExercise.java
> +                }
Also, what happens when:
1. a start event with t=1s arrives and sets the timer
2. after two hours the timer triggers and clears the registeredRide state
3. an end event with t=3h arrives and gets stored in the state

2024-07-12 05:31 UTC, ness-PavelKhokhlov requested changes
Hello, according to instructions:
"6. Switch to branch "release-1.15"
in your case you're using `master` branch which is wrong

2024-07-12 07:52 UTC, Cristian34 commented on long-ride-alerts/src/main/java/org/apache/flink/training/exercises/longrides/LongRidesExercise.java
> +        private ValueState<TaxiRide> registeredRide;
Done

2024-07-12 07:55 UTC, Cristian34 commented on long-ride-alerts/src/main/java/org/apache/flink/training/exercises/longrides/LongRidesExercise.java
> +                    registeredRide.update(ride);
Indeed, this is a valid point. 
As a simple solution, I could try to set up an expiration time on the state, but this won't provide as much flexibility and it may not work properly with event time historical data.
Therefore, I created another timer for expiring idle state, which will take care of idle state for END events.
For START events we don't need this timer, since we have the timer for "long duration" which cleans up state when triggered.

2024-07-12 07:55 UTC, Cristian34 commented on long-ride-alerts/src/main/java/org/apache/flink/training/exercises/longrides/LongRidesExercise.java
> +                }
Provided timer, as described above.

2024-07-12 08:23 UTC, ness-RazvanFilip commented on long-ride-alerts/src/main/java/org/apache/flink/training/exercises/longrides/LongRidesExercise.java
> +                }
I think it is ok

2024-07-12 08:24 UTC, ness-RazvanFilip approved these changes

2024-07-12 08:29 UTC, Cristian34 commented
> Hello, according to instructions: "6. Switch to branch "release-1.15" in your case you're using `master` branch which is wrong

The branch was correctly created, from "release-1.15", but the pull request destination was wrong.
I've updated the pull request to point to the requested destination.
@ness-PavelKhokhlov, could you approve the pull request, please?

2024-07-14 05:12 UTC, ness-PavelKhokhlov approved these changes

2024-07-15 06:33 UTC, merged